/**
 * backend
 * backend
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: dan_franco_15@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: NewUserRequest, schemaOptions: { title: \'NewUser\' })
 */
export interface NewUser { 
    name: string;
    email: string;
    id?: string;
    premium?: boolean;
    password: string;
}

